#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Feb 27 20:26:03 EST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 2b7549c656754af3b7bb2fcf988c5818 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_gen_behav xil_defaultlib.clock_gen -log elaborate.log"
xelab -wto 2b7549c656754af3b7bb2fcf988c5818 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_gen_behav xil_defaultlib.clock_gen -log elaborate.log

