@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Feb 22 15:09:15 -0500 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 84a35f44ddf9431893fa773d727487e1 --incr --debug typical --relax --mt 2 -L work -L xil_defaultlib -L secureip --snapshot tb_CoraZ7_behav xil_defaultlib.tb_CoraZ7 -log elaborate.log"
call xelab  -wto 84a35f44ddf9431893fa773d727487e1 --incr --debug typical --relax --mt 2 -L work -L xil_defaultlib -L secureip --snapshot tb_CoraZ7_behav xil_defaultlib.tb_CoraZ7 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
