#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Feb 27 03:32:16 EST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a77c0f67263f46c4a7de1b3990d2d7c9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cora_wrapper_behav xil_defaultlib.cora_wrapper -log elaborate.log"
xelab -wto a77c0f67263f46c4a7de1b3990d2d7c9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cora_wrapper_behav xil_defaultlib.cora_wrapper -log elaborate.log

