#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 01 14:30:53 EST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto bade65d856d84da2aa0cba8b2edf716b --incr --debug typical --relax --mt 8 -L work -L secureip --snapshot vivado_tb_CoraZ7_behav work.vivado_tb_CoraZ7 -log elaborate.log"
xelab -wto bade65d856d84da2aa0cba8b2edf716b --incr --debug typical --relax --mt 8 -L work -L secureip --snapshot vivado_tb_CoraZ7_behav work.vivado_tb_CoraZ7 -log elaborate.log

