#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 01 14:30:55 EST 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim vivado_tb_CoraZ7_behav -key {Behavioral:sim_1:Functional:vivado_tb_CoraZ7} -tclbatch vivado_tb_CoraZ7.tcl -view /home/spixy/Documents/College/EE316/EE316P3/EE316P3/master/master.sim/sim_1/vivado_tb_CoraZ7_behav.wcfg -log simulate.log"
xsim vivado_tb_CoraZ7_behav -key {Behavioral:sim_1:Functional:vivado_tb_CoraZ7} -tclbatch vivado_tb_CoraZ7.tcl -view /home/spixy/Documents/College/EE316/EE316P3/EE316P3/master/master.sim/sim_1/vivado_tb_CoraZ7_behav.wcfg -log simulate.log

